---
- hosts: leaf:spine
  remote_user: cumulus
  become: yes
  become_method: sudo
  roles:
    - ifupdown2
    - quagga

- hosts: server
  remote_user: cumulus
  become: yes
  become_method: sudo
  roles:
    - ifupdown


