---
- hosts: leaf:spine
  become: yes
  gather_facts: no
  vars:
      #Collect the Current date and time from the local system
      current_date: "{{ lookup('pipe', 'date +\"%F_%T\"') }}"
  tasks:
    - name: Create a Directory to Store Configuration Files Locally
      file: path=configuration_storage/{{ inventory_hostname }} state=directory recurse=yes
      delegate_to: localhost
      become: no

    - name: Run show config commands
      shell: 'net show config commands | grep net | grep -v "del all" > {{inventory_hostname}}_nclu'
      # Explanation of  grep commands
      # '| grep net' removes all non-net commands (e.g. comments)
      # '| grep -v "del all"' removes the del all command from the beginning of the output, otherwise replay won't be idempotent
      
    - name: Fetch the file and store it locally (Dated Version)
      fetch: dest=configuration_storage/{{inventory_hostname}}/{{current_date}}_nclu_based_configuration src=/home/cumulus/{{inventory_hostname}}_nclu flat=yes
      # This task grabs the output from the previous command and stores it as a flat-file locally on the machine running ansible
      
    - name: Fetch the file and store it locally (Current Version)
      fetch: dest=configuration_storage/{{inventory_hostname}}/current_nclu_based_configuration src=/home/cumulus/{{inventory_hostname}}_nclu flat=yes


      #The next two stanzas are not required, but grabs the rendered flat-file config if you prefer them over NCLU (net) commands
      
    - name: Run show config files
      shell: 'net show config files > {{inventory_hostname}}_config_files'
      # This grabs all the rendered configurations (vs the net commands)

    - name: Fetch the file and store it locally (Dated Version)
      fetch: dest=configuration_storage/{{inventory_hostname}}/{{current_date}}_flat_file_configuration src=/home/cumulus/{{inventory_hostname}}_config_files flat=yes
      # This task grabs the rendered configuration from the previous command and stores it locally on the machine running ansible

    - name: Fetch the file and store it locally (Current Version)
      fetch: dest=configuration_storage/{{inventory_hostname}}/current_flat_file_configuration src=/home/cumulus/{{inventory_hostname}}_config_files flat=yes
